  
name: Test Setup

on: 
  push:
    branches: [main]
  schedule:
    - cron: "* * * * *"

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go env
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.4'
      - name: Check Go version
        run: go version
          
